/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RoleSwitcherRouteImport } from './routes/role-switcher'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as EventIdIndexRouteImport } from './routes/event.$id.index'
import { Route as EventIdSuccessRouteImport } from './routes/event.$id.success'
import { Route as EventIdProcessingRouteImport } from './routes/event.$id.processing'
import { Route as EventIdPaymentRouteImport } from './routes/event.$id.payment'
import { Route as EventIdCheckoutRouteImport } from './routes/event.$id.checkout'
import { Route as OrganizerEventIdIndexRouteImport } from './routes/organizer.event.$id.index'
import { Route as OrganizerEventIdScannerRouteImport } from './routes/organizer.event.$id.scanner'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSwitcherRoute = RoleSwitcherRouteImport.update({
  id: '/role-switcher',
  path: '/role-switcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdIndexRoute = EventIdIndexRouteImport.update({
  id: '/event/$id/',
  path: '/event/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdSuccessRoute = EventIdSuccessRouteImport.update({
  id: '/event/$id/success',
  path: '/event/$id/success',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdProcessingRoute = EventIdProcessingRouteImport.update({
  id: '/event/$id/processing',
  path: '/event/$id/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdPaymentRoute = EventIdPaymentRouteImport.update({
  id: '/event/$id/payment',
  path: '/event/$id/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdCheckoutRoute = EventIdCheckoutRouteImport.update({
  id: '/event/$id/checkout',
  path: '/event/$id/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventIdIndexRoute = OrganizerEventIdIndexRouteImport.update({
  id: '/organizer/event/$id/',
  path: '/organizer/event/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventIdScannerRoute = OrganizerEventIdScannerRouteImport.update({
  id: '/organizer/event/$id/scanner',
  path: '/organizer/event/$id/scanner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/role-switcher': typeof RoleSwitcherRoute
  '/saved': typeof SavedRoute
  '/tickets': typeof TicketsRoute
  '/ticket/$id': typeof TicketIdRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/event/$id/checkout': typeof EventIdCheckoutRoute
  '/event/$id/payment': typeof EventIdPaymentRoute
  '/event/$id/processing': typeof EventIdProcessingRoute
  '/event/$id/success': typeof EventIdSuccessRoute
  '/event/$id/': typeof EventIdIndexRoute
  '/organizer/event/$id/scanner': typeof OrganizerEventIdScannerRoute
  '/organizer/event/$id/': typeof OrganizerEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/role-switcher': typeof RoleSwitcherRoute
  '/saved': typeof SavedRoute
  '/tickets': typeof TicketsRoute
  '/ticket/$id': typeof TicketIdRoute
  '/organizer': typeof OrganizerIndexRoute
  '/event/$id/checkout': typeof EventIdCheckoutRoute
  '/event/$id/payment': typeof EventIdPaymentRoute
  '/event/$id/processing': typeof EventIdProcessingRoute
  '/event/$id/success': typeof EventIdSuccessRoute
  '/event/$id': typeof EventIdIndexRoute
  '/organizer/event/$id/scanner': typeof OrganizerEventIdScannerRoute
  '/organizer/event/$id': typeof OrganizerEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/role-switcher': typeof RoleSwitcherRoute
  '/saved': typeof SavedRoute
  '/tickets': typeof TicketsRoute
  '/ticket/$id': typeof TicketIdRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/event/$id/checkout': typeof EventIdCheckoutRoute
  '/event/$id/payment': typeof EventIdPaymentRoute
  '/event/$id/processing': typeof EventIdProcessingRoute
  '/event/$id/success': typeof EventIdSuccessRoute
  '/event/$id/': typeof EventIdIndexRoute
  '/organizer/event/$id/scanner': typeof OrganizerEventIdScannerRoute
  '/organizer/event/$id/': typeof OrganizerEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/role-switcher'
    | '/saved'
    | '/tickets'
    | '/ticket/$id'
    | '/organizer/'
    | '/event/$id/checkout'
    | '/event/$id/payment'
    | '/event/$id/processing'
    | '/event/$id/success'
    | '/event/$id/'
    | '/organizer/event/$id/scanner'
    | '/organizer/event/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/role-switcher'
    | '/saved'
    | '/tickets'
    | '/ticket/$id'
    | '/organizer'
    | '/event/$id/checkout'
    | '/event/$id/payment'
    | '/event/$id/processing'
    | '/event/$id/success'
    | '/event/$id'
    | '/organizer/event/$id/scanner'
    | '/organizer/event/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/role-switcher'
    | '/saved'
    | '/tickets'
    | '/ticket/$id'
    | '/organizer/'
    | '/event/$id/checkout'
    | '/event/$id/payment'
    | '/event/$id/processing'
    | '/event/$id/success'
    | '/event/$id/'
    | '/organizer/event/$id/scanner'
    | '/organizer/event/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RoleSwitcherRoute: typeof RoleSwitcherRoute
  SavedRoute: typeof SavedRoute
  TicketsRoute: typeof TicketsRoute
  TicketIdRoute: typeof TicketIdRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  EventIdCheckoutRoute: typeof EventIdCheckoutRoute
  EventIdPaymentRoute: typeof EventIdPaymentRoute
  EventIdProcessingRoute: typeof EventIdProcessingRoute
  EventIdSuccessRoute: typeof EventIdSuccessRoute
  EventIdIndexRoute: typeof EventIdIndexRoute
  OrganizerEventIdScannerRoute: typeof OrganizerEventIdScannerRoute
  OrganizerEventIdIndexRoute: typeof OrganizerEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-switcher': {
      id: '/role-switcher'
      path: '/role-switcher'
      fullPath: '/role-switcher'
      preLoaderRoute: typeof RoleSwitcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/': {
      id: '/event/$id/'
      path: '/event/$id'
      fullPath: '/event/$id/'
      preLoaderRoute: typeof EventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/success': {
      id: '/event/$id/success'
      path: '/event/$id/success'
      fullPath: '/event/$id/success'
      preLoaderRoute: typeof EventIdSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/processing': {
      id: '/event/$id/processing'
      path: '/event/$id/processing'
      fullPath: '/event/$id/processing'
      preLoaderRoute: typeof EventIdProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/payment': {
      id: '/event/$id/payment'
      path: '/event/$id/payment'
      fullPath: '/event/$id/payment'
      preLoaderRoute: typeof EventIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/checkout': {
      id: '/event/$id/checkout'
      path: '/event/$id/checkout'
      fullPath: '/event/$id/checkout'
      preLoaderRoute: typeof EventIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/event/$id/': {
      id: '/organizer/event/$id/'
      path: '/organizer/event/$id'
      fullPath: '/organizer/event/$id/'
      preLoaderRoute: typeof OrganizerEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/event/$id/scanner': {
      id: '/organizer/event/$id/scanner'
      path: '/organizer/event/$id/scanner'
      fullPath: '/organizer/event/$id/scanner'
      preLoaderRoute: typeof OrganizerEventIdScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RoleSwitcherRoute: RoleSwitcherRoute,
  SavedRoute: SavedRoute,
  TicketsRoute: TicketsRoute,
  TicketIdRoute: TicketIdRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  EventIdCheckoutRoute: EventIdCheckoutRoute,
  EventIdPaymentRoute: EventIdPaymentRoute,
  EventIdProcessingRoute: EventIdProcessingRoute,
  EventIdSuccessRoute: EventIdSuccessRoute,
  EventIdIndexRoute: EventIdIndexRoute,
  OrganizerEventIdScannerRoute: OrganizerEventIdScannerRoute,
  OrganizerEventIdIndexRoute: OrganizerEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
